octomap_resolution: 0.005
sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: filtered_cloud
  max_range: 0.50
  max_update_rate: 1.0
  padding_offset: 0.01
  padding_scale: 1.0
  point_cloud_topic: /camera/camera/depth/color/points
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater